server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true

spring:
  application:
    name: user-service

  docker:
    compose:
      enabled: false

  spring:
  data:
    mongodb:
      host: ${USER_MONGO_HOST:localhost}
      port: ${USER_MONGO_PORT:27017}
      database: ${USER_MONGO_DB:user_db}
      username: ${USER_MONGO_USERNAME:user_service}
      password: ${USER_MONGO_PASSWORD:user_password}
      authentication-database: admin

security:
  jwt:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

media:
  service:
    url: ${MEDIA_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
