# jenkins
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8084:8080"   
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins-data:/var/jenkins-data
      # Optional: Mount the docker socket to run docker commands inside Jenkins
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data: