services:
  mongodb:
    container_name: ${PRODUCT_MONGO_DB_NAME}
    image: mongo:latest
    ports:
      - "${PRODUCT_MONGO_LOCAL_PORT}:${PRODUCT_MONGO_DOCKER_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${PRODUCT_MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${PRODUCT_MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PRODUCT_MONGO_DB_PWD}
    volumes:
      - product-mongo-data:/data/db

volumes:
  product-mongo-data:
