server:
  port: 8083

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 50MB
  data:
    mongodb:
      host: ${MEDIA_MONGO_HOST:localhost}
      port: ${MEDIA_MONGO_LOCAL_PORT:27018}
      database: ${MEDIA_MONGO_DB_NAME:mongo-media}
      username: ${MEDIA_MONGO_DB_USER:rserraf}
      password: ${MEDIA_MONGO_DB_PWD:123456}
      authentication-database: admin
      
  kafka:
    consumer:
      group-id: media-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true
