server:
  port: 8082

spring:
  application:
    name: product-service
  mongodb:
    uri: "mongodb://${PRODUCT_MONGO_DB_USER}:${PRODUCT_MONGO_DB_PWD}@localhost:${PRODUCT_MONGO_LOCAL_PORT}/${PRODUCT_MONGO_DB_NAME}?authSource=admin"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true

services:
  media: "http://localhost:8083"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
